config/routes.rb
Pinplug::Application.routes.draw do
  resources :plugs

  devise_for :users 

  root 'plugs#index'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
end

end

app/models/plug.rb
class Plug < ActiveRecord::Base
belongs_to :user

has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

validates :description, presence: true
validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :plugs

validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

end

app/controllers/plugs_controller.rb
class PlugsController < ApplicationController
  before_action :set_plug, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /plugs
  def index
    @plugs = Plug.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /plugs/1
  def show
  end

  # GET /plugs/new
  def new
    @plug = current_user.plugs.build
  end

  # GET /plugs/1/edit
  def edit
  end

  # POST /plugs
  def create
    @plug = current_user.plugs.build(plug_params)

      if @plug.save
        redirect_to @plug, notice: 'Plug was successfully created.' 
      else
        render :new 
      end
    end
  

  # PATCH/PUT /plugs/1
  def update
    
      if @plug.update(plug_params)
        redirect_to @plug, notice: 'Plug was successfully updated.'  
      else
        render :edit   
    end
  end

  # DELETE /plugs/1
  def destroy
    @plug.destroy
    
     redirect_to plugs_url, notice: 'Plug was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plug
      @plug = Plug.find(params[:id])
    end

    def correct_user
        @plug = current_user.plugs.find_by(id: params[:id])
        redirect_to plugs_path, notice: "Not authorized to edit this plug" if @plug.nil?
      end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plug_params
      params.require(:plug).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plugs_helper.rb
module PlugsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container"> 
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Pinplug", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to new_plug_path do %>
                <span class="glyphicon glyphicon-plus"></span> New Plug <% end %></li>
          <li><%= link_to"Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %> 
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinplug</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
		<%= yield %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
<h1>Welcome to Pinplug!</h1>


	<p><%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
	   <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	 </p>
	 
</div>

app/views/pages/about.html.erb
<h1>About US</h1>
<p>We are working on our One Month Rails Pinplug Application</p>

app/views/pages/contact.html.erb
<h1>Contact US</h1>
<p>You can contact us at butlerteamgreen@gmail.com</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1>Welcome to Pinplug!</h1>
	<% if user_signed_in? %>
		# do something
	<% else %>

	<p><%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
	   <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	 </p>
	 <% end %>
</div>

app/views/plugs/_form.html.erb
<%= form_for @plug, html: {multipart: true} do |f| %>
  <% if @plug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plug.errors.count, "error") %> prohibited this plug from being saved:</h2>

      <ul>
      <% @plug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :Description %>
    <%= f.text_field :description, class: "form-control" %>
     </div>
     <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/plugs/edit.html.erb
<h1>Editing Plug</h1>

<%= render 'form' %>

<%= link_to 'Show', @plug %> |
<%= link_to 'Back', plugs_path %>

app/views/plugs/index.html.erb
  <%= render 'pages/home' unless user_signed_in? %>

  <div id="plugs" class="transitions-enabled">
    <% @plugs.each do |plug| %>
      <div class="box panel panel-default">
        <%= link_to image_tag(plug.image.url(:medium)), plug %>
        <div class="panel-body">
         <p> <%= plug.description %></p>
          <p><strong><%= plug.user.name if plug.user %></strong></p>
          <% if plug.user == current_user %>
          <div class="actions">
          <%= link_to edit_plug_path(plug) do %>
          <span class="glyphicon glyphicon-edit"></span>
          Edit
          <% end %>
          <%= link_to plug, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
            Delete
            <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  
</div>


<div class="center">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/plugs/new.html.erb
<h1>New Plug</h1>

<%= render 'form' %>

<%= link_to 'Back', plugs_path %>

app/views/plugs/show.html.erb
<%= link_to 'Back', plugs_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
<%= image_tag @plug.image.url(:medium) %>
</div>
<div class="panel-body">
<p><%= @plug.description %></p>
<p><strong><%= @plug.user.name if @plug.user %></strong></p>

<% if @plug.user == current_user %>
	     <%= link_to edit_plug_path(@plug) do %>
       <span class="glyphicon glyphicon-edit"></span>
          Edit
      <% end %> 
<% end %>

      </div>
    </div>
  </div>
</div>